import os

p2_minecarts = ','.join([f'{{slot:{i},item:{{id:"minecraft:tnt_minecart",count:1}}}}' for i in range(6, 22)])
p3_minecarts = ','.join([f'{{slot:{i},item:{{id:"minecraft:tnt_minecart",count:1}}}}' for i in range(6, 22)])

slots = [
    # slot 0: Stab-Shot resources
    '{slot:0,item:{id:"minecraft:yellow_shulker_box",count:1,components:{custom_name:\'{"italic":false,"color":"yellow","bold":true,"text":"Ресурсы | Stab-Shot"}\',container:[{slot:0,item:{id:"minecraft:fishing_rod",count:1,components:{custom_data:{stabshot:1b},custom_name:\'{"italic":false,"color":"aqua","bold":true,"text":"Stab-Shot"}\',rarity:"rare",damage:63}}},{slot:1,item:{id:"minecraft:blaze_rod",count:64}},{slot:2,item:{id:"minecraft:ghast_tear",count:64}},{slot:3,item:{id:"minecraft:tnt",count:64}},{slot:4,item:{id:"minecraft:tnt_minecart",count:1}},{slot:5,item:{id:"minecraft:tnt_minecart",count:1}},{slot:6,item:{id:"minecraft:blaze_powder",count:64}},{slot:7,item:{id:"minecraft:nether_star",count:16}},{slot:8,item:{id:"minecraft:spectral_arrow",count:64}}]}}}',
    # slot 1: Wither-Shot resources
    '{slot:1,item:{id:"minecraft:purple_shulker_box",count:1,components:{custom_name:\'{"italic":false,"color":"dark_purple","bold":true,"text":"Ресурсы | Wither-Shot"}\',container:[{slot:0,item:{id:"minecraft:fishing_rod",count:1,components:{custom_data:{withershot:1b},custom_name:\'{"italic":false,"color":"dark_purple","text":"Wither-Shot"}\',rarity:"epic",damage:63}}},{slot:1,item:{id:"minecraft:wither_skeleton_skull",count:64}},{slot:2,item:{id:"minecraft:tnt",count:64}},{slot:3,item:{id:"minecraft:obsidian",count:64}}]}}}',
    # slot 2: Fire-Shot resources
    '{slot:2,item:{id:"minecraft:orange_shulker_box",count:1,components:{custom_name:\'{"italic":false,"color":"gold","bold":true,"text":"Ресурсы | Fire-Shot (Миномет)"}\',container:[{slot:0,item:{id:"minecraft:crossbow",count:1,components:{custom_data:{orbital_mortar_bow:1b,fireshot:1b},custom_name:\'{"color":"gold","text":"Орбитальный Миномет"}\'}}},{slot:1,item:{id:"minecraft:firework_rocket",count:64,components:{custom_data:{orbital_rocket:1b},custom_name:\'{"color":"red","text":"Орбитальный Снаряд"}\'}}},{slot:2,item:{id:"minecraft:tnt",count:64}},{slot:3,item:{id:"minecraft:blaze_powder",count:64}}]}}}',
    # slot 3: Archi-Shield resources
    '{slot:3,item:{id:"minecraft:blue_shulker_box",count:1,components:{custom_name:\'{"italic":false,"color":"blue","bold":true,"text":"Ресурсы | Archi-Shield (Архи-Щит)"}\',container:[{slot:0,item:{id:"minecraft:shield",count:1,components:{custom_data:{archi_shield:1b},max_damage:1680,custom_name:\'{"color":"gold","bold":true,"text":"Архи-Щит"}\'}}},{slot:1,item:{id:"minecraft:obsidian",count:64}},{slot:2,item:{id:"minecraft:netherite_ingot",count:16}}]}}}',
    # slot 4: NukeShot P1
    '{slot:4,item:{id:"minecraft:red_shulker_box",count:1,components:{custom_name:\'{"italic":false,"color":"red","bold":true,"text":"Ресурсы | NukeShot (Power-1)"}\',container:[{slot:0,item:{id:"minecraft:fishing_rod",count:1,components:{custom_data:{nukeshot:1b,nukeshot_power:1,power_level:1,nukeshot_p1:1b,power_tag:"power_1"},custom_model_data:{floats:[1001.0]},custom_name:\'{"italic":false,"color":"red","text":"NukeShot | Power-1"}\',rarity:"rare",damage:63}}},{slot:1,item:{id:"minecraft:netherite_block",count:1}},{slot:2,item:{id:"minecraft:nether_star",count:1}},{slot:3,item:{id:"minecraft:end_crystal",count:4}},{slot:4,item:{id:"minecraft:wither_skeleton_skull",count:3}},{slot:5,item:{id:"minecraft:tnt",count:64}}]}}}',
    # slot 5: NukeShot P2
    f'{{slot:5,item:{{id:"minecraft:magenta_shulker_box",count:1,components:{{custom_name:\'{{"italic":false,"color":"light_purple","bold":true,"text":"Ресурсы | NukeShot (Power-2)"}}\',container:[{{slot:0,item:{{id:"minecraft:fishing_rod",count:1,components:{{custom_data:{{nukeshot:1b,nukeshot_power:2,power_level:2,nukeshot_p2:1b,power_tag:"power_2"}},custom_model_data:{{floats:[1002.0]}},custom_name:\'{{"italic":false,"color":"red","text":"NukeShot | Power-2"}}\',rarity:"rare",damage:63}}}}}},{{slot:1,item:{{id:"minecraft:netherite_block",count:3}}}},{{slot:2,item:{{id:"minecraft:nether_star",count:2}}}},{{slot:3,item:{{id:"minecraft:end_crystal",count:8}}}},{{slot:4,item:{{id:"minecraft:wither_skeleton_skull",count:6}}}},{{slot:5,item:{{id:"minecraft:ghast_tear",count:16}}}},{p2_minecarts}]}}}}',
    # slot 6: NukeShot P3
    f'{{slot:6,item:{{id:"minecraft:pink_shulker_box",count:1,components:{{custom_name:\'{{"italic":false,"color":"dark_red","bold":true,"text":"Ресурсы | NukeShot (Power-3)"}}\',container:[{{slot:0,item:{{id:"minecraft:fishing_rod",count:1,components:{{custom_data:{{nukeshot:1b,nukeshot_power:3,power_level:3,nukeshot_p3:1b,power_tag:"power_3"}},custom_model_data:{{floats:[1003.0]}},custom_name:\'{{"italic":false,"color":"dark_red","text":"NukeShot | Power-3"}}\',rarity:"epic",damage:63}}}}}},{{slot:1,item:{{id:"minecraft:netherite_block",count:6}}}},{{slot:2,item:{{id:"minecraft:nether_star",count:4}}}},{{slot:3,item:{{id:"minecraft:end_crystal",count:16}}}},{{slot:4,item:{{id:"minecraft:beacon",count:1}}}},{{slot:5,item:{{id:"minecraft:dragon_breath",count:4}}}},{p3_minecarts}]}}}}',
    # slot 7: NukeShot P4
    '{slot:7,item:{id:"minecraft:cyan_shulker_box",count:1,components:{custom_name:\'{"italic":false,"color":"dark_red","bold":true,"text":"Ресурсы | NukeShot (Power-4)"}\',container:[{slot:0,item:{id:"minecraft:fishing_rod",count:1,components:{custom_data:{nukeshot:1b,nukeshot_power:4,power_level:4,nukeshot_p4:1b,power_tag:"power_4"},custom_model_data:{floats:[1004.0]},custom_name:\'{"italic":false,"color":"dark_red","text":"NukeShot | Power-4"}\',rarity:"epic",damage:63}}},{slot:1,item:{id:"minecraft:netherite_block",count:64}},{slot:2,item:{id:"minecraft:nether_star",count:64}},{slot:3,item:{id:"minecraft:end_crystal",count:64}},{slot:4,item:{id:"minecraft:beacon",count:64}}]}}}'
]

cmd = 'give @s chest[container=[' + ','.join(slots) + ']]'

target = r'c:\Users\1\AppData\Roaming\ModrinthApp\profiles\Cozy Modpack by remkkic\saves\Nuke-проверка\datapacks\orbital_v7_1\data\nuke\function\give\chest_of_shulkers.mcfunction'
with open(target, 'w', encoding='utf-8') as f:
    f.write(cmd + '\n')
print("Successfully generated chest_of_shulkers.mcfunction!")
